apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"

  security:
    authentication:
      modes: ["SCRAM"]
    roles:
      - db: admin
        privileges:
          - actions:
              - find
            resource:
              collection: ''
              db: ''
        role: testRole
        roles: []
  users:
    - name: admin-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-user-password
        key: password
      roles:
        - db: admin
          name: clusterAdmin
        - db: admin
          name: userAdminAnyDatabase
        - db: admin
          name: readWrite
        - db: admin
          name: testRole
        - db: admin
          name: dbAdminAnyDatabase
        - db: admin
          name: readWriteAnyDatabase
      scramCredentialsSecretName: mongodb-admin-user-password
    # Example of additional users
    # - name: user1
    #   db: app
    #   roles:
    #     - name: readWrite
    #       db: app
    #   passwordSecretRef:
    #     name: user1-password-secret
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib